# Generated by Django 3.1.6 on 2021-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='static/products')),
                ('product_price', models.FloatField()),
                ('product_size', models.CharField(max_length=30)),
                ('product_colors', models.CharField(max_length=20)),
                ('units_in_stock', models.IntegerField()),
                ('units_in_order', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
