# Generated by Django 3.2 on 2021-05-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210522_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building_number',
            new_name='add1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='add2',
        ),
    ]
